server:
  port: 8080
  session:
    timeout: 3600

### Begin Spring ### 
spring:
  freemarker:
    enabled: true
#    cache: false
#    charset: UTF-8
#    suffix: ftl
    template-loader-path:
      - classpath:/templates/
#      - file:src/main/resources/templates
#    settings:
#      url_escaping_charset: UTF-8
#      output_format: HTMLOutputFormat
#      lazy_auto_imports: true
#      #auto_import: /spring.ftl as spring
#      # 例外の処理モード。
#      # 開発時は html_debug 本番は rethrow を指定する。
#      template_exception_handler: html_debug
    expose-request-attributes: true
    expose-spring-macro-helpers: true
    
# static resource
#  resources:
#    static-locations: classpath:/static/

# jdbc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.56.2:5432/testdb
    username: testdb_user
    password: testdb_user_01

# jpa
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  # 1.5.9で必須に
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # session
  session:
    store-type: hash-map
    
### End Spring ### 
 
# spring-boot actuator
management:
  context-path: /sysconfig
  security:
    enabled: false
    
endpoints:
  health:
    sensitive: false

logging:
#  file: logs/info.log
  level:
    org.springframework.web: INFO
                          
# security
security:
  basic:
    enabled: false
